#ifndef STELLAR_LIBSMB2_PRIVATE_SHIM_H
#define STELLAR_LIBSMB2_PRIVATE_SHIM_H

#include <stdint.h>
#include <time.h>

#define smb2_init_context stellar_user_media_sdk_libsmb2_smb2_init_context
#define smb2_close_context stellar_user_media_sdk_libsmb2_smb2_close_context
#define smb2_destroy_context stellar_user_media_sdk_libsmb2_smb2_destroy_context
#define smb2_set_timeout stellar_user_media_sdk_libsmb2_smb2_set_timeout
#define smb2_set_version stellar_user_media_sdk_libsmb2_smb2_set_version
#define smb2_set_security_mode stellar_user_media_sdk_libsmb2_smb2_set_security_mode
#define smb2_set_sign stellar_user_media_sdk_libsmb2_smb2_set_sign
#define smb2_set_seal stellar_user_media_sdk_libsmb2_smb2_set_seal
#define smb2_set_authentication stellar_user_media_sdk_libsmb2_smb2_set_authentication
#define smb2_set_domain stellar_user_media_sdk_libsmb2_smb2_set_domain
#define smb2_set_user stellar_user_media_sdk_libsmb2_smb2_set_user
#define smb2_set_password stellar_user_media_sdk_libsmb2_smb2_set_password
#define smb2_connect_share stellar_user_media_sdk_libsmb2_smb2_connect_share
#define smb2_disconnect_share stellar_user_media_sdk_libsmb2_smb2_disconnect_share
#define smb2_get_dialect stellar_user_media_sdk_libsmb2_smb2_get_dialect
#define smb2_get_error stellar_user_media_sdk_libsmb2_smb2_get_error
#define smb2_get_nterror stellar_user_media_sdk_libsmb2_smb2_get_nterror
#define nterror_to_errno stellar_user_media_sdk_libsmb2_nterror_to_errno
#define smb2_opendir stellar_user_media_sdk_libsmb2_smb2_opendir
#define smb2_readdir stellar_user_media_sdk_libsmb2_smb2_readdir
#define smb2_closedir stellar_user_media_sdk_libsmb2_smb2_closedir
#define smb2_stat stellar_user_media_sdk_libsmb2_smb2_stat
#define smb2_open stellar_user_media_sdk_libsmb2_smb2_open
#define smb2_get_max_read_size stellar_user_media_sdk_libsmb2_smb2_get_max_read_size
#define smb2_pread stellar_user_media_sdk_libsmb2_smb2_pread
#define smb2_close stellar_user_media_sdk_libsmb2_smb2_close

#include <smb2/smb2.h>
#include <smb2/libsmb2.h>

#endif
