#!/usr/bin/env python3
"""Generate the Swift schema resource from canonical cross-platform SQL."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


HEADER = """// Generated by tools/storage/generate_swift_sql_schemas.py. Do not edit.

extension StorageDatabaseKind {
  var schemaSQL: String {
    switch self {
"""

FOOTER = """    }
  }

  func canonicalSchemaChecksum(version: Int) -> String? {
    switch (self, version) {
__CHECKSUM_CASES__    default: nil
    }
  }

  func migrationSQL(fromVersion: Int) -> String? {
    switch (self, fromVersion) {
__MIGRATION_CASES__    default: nil
    }
  }
}
"""


def render(root: Path) -> str:
    manifest_path = root / "specs/storage/schema-manifest-v1.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    cases: list[str] = []
    checksum_cases: list[str] = []
    migration_cases: list[str] = []
    swift_cases = {
        "account": "account",
        "library": "library",
        "metadata_cache": "metadataCache",
    }

    for definition in manifest["databases"]:
        name = definition["name"]
        path = manifest_path.parent / definition["file"]
        content = path.read_bytes()
        checksum = hashlib.sha256(content).hexdigest()
        if checksum != definition["sha256"]:
            raise ValueError(f"{name} checksum does not match the reviewed manifest")
        sql = content.decode("utf-8").rstrip("\n")
        indented_sql = "\n".join(f"      {line}" if line else "" for line in sql.splitlines())
        cases.append(
            f'    case .{swift_cases[name]}:\n      #"""\n{indented_sql}\n      """#\n'
        )
        version = definition["user_version"]
        checksum_cases.append(
            f'    case (.{swift_cases[name]}, {version}): "{checksum}"\n'
        )

    migrations_path = root / "specs/storage/schema-migrations.json"
    migrations = json.loads(migrations_path.read_text(encoding="utf-8"))
    for definition in migrations["migrations"]:
        name = definition["name"]
        path = migrations_path.parent / definition["file"]
        content = path.read_bytes()
        checksum = hashlib.sha256(content).hexdigest()
        if checksum != definition["sha256"]:
            raise ValueError(f"{name} v{definition['to_version']} checksum does not match")
        sql = content.decode("utf-8").rstrip("\n")
        indented_sql = "\n".join(f"      {line}" if line else "" for line in sql.splitlines())
        migration_cases.append(
            f'    case (.{swift_cases[name]}, {definition["from_version"]}):\n'
            f'      #"""\n{indented_sql}\n      """#\n'
        )
        checksum_cases.append(
            f'    case (.{swift_cases[name]}, {definition["to_version"]}): "{checksum}"\n'
        )

    return (
        HEADER
        + "".join(cases)
        + FOOTER.replace("__CHECKSUM_CASES__", "".join(checksum_cases)).replace(
            "__MIGRATION_CASES__", "".join(migration_cases)
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    output = args.output
    if not output.is_absolute():
        output = root / output

    try:
        generated = render(root)
    except (KeyError, OSError, UnicodeDecodeError, ValueError, json.JSONDecodeError) as error:
        print(f"Swift schema generation failed: {error}")
        return 1

    if args.check:
        try:
            existing = output.read_text(encoding="utf-8")
        except OSError as error:
            print(f"Swift schema generation check failed: {error}")
            return 1
        if existing != generated:
            print(f"Swift schema generation check failed: regenerate {output}")
            return 1
        print("Swift schema generation check passed")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8")
    print(f"Generated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
